# Generated by Django 4.1.1 on 2022-09-10 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_name', models.CharField(blank=True, max_length=200)),
                ('ticket_type', models.CharField(blank=True, max_length=200)),
                ('ticket_description', models.TextField(blank=True, max_length=200)),
                ('ticket_status', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='is_Officer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='is_Student',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=20, unique='True'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_related_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('reg_no', models.IntegerField(null=True, unique=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_related_ticket', to='base.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='officer_related_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=100, null=True, unique=True)),
                ('role', models.CharField(max_length=20, null=True)),
                ('officer_verified', models.BooleanField(default=False)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officer_related_ticket', to='base.ticket')),
            ],
        ),
    ]
