# Generated by Django 4.1.1 on 2022-10-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reg_no',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
