# Generated by Django 4.1.1 on 2022-09-29 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_ticket_reg_no_alter_users_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['created_by']},
        ),
    ]
