# Generated by Django 4.1.1 on 2022-09-10 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_ticket_users_is_officer_users_is_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officer',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['ticket_name']},
        ),
    ]
