# Generated by Django 4.1.1 on 2022-09-29 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_by']},
        ),
    ]
