# Generated by Django 4.1.1 on 2022-09-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_officer_created_at_officer_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Deferred', 'Deferred')], default='Open', max_length=200),
        ),
    ]
