# Generated by Django 4.1.1 on 2022-09-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_ticket_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(blank=True, choices=[('InProgress', 'InProgress'), ('Open', 'Open'), ('Closed', 'Closed'), ('Deferred', 'Deferred')], default='Open', max_length=200),
        ),
    ]
